# Максимальная скорость, которую лодка может развить на льду.
max-ice-speed: 5.5

# Максимальная скорость ВНЕ ЛЬДА (на земле, в воде и т.д.).
# Позволяет игроку выехать обратно на трассу, если он вылетел.
# (Vanilla скорость на земле ~0.1-0.2, в воде ~0.35).
# Рекомендуемое значение: 0.45 (чуть быстрее, чем в воде).
max-off-ice-speed: 0.45

# ПРИРОСТ УСКОРЕНИЯ. Насколько скорость увеличивается каждый тик при нажатии W.
acceleration-amount: 0.025

# КОЭФФИЦИЕНТ ЗАМЕДЛЕНИЯ (НА ЛЬДУ). Плавность скольжения, когда клавиша W отпущена.
# Чем ближе к 1.0, тем дольше лодка скользит.
deceleration-factor: 0.98

# ФАКТОР ПОТЕРИ ИНЕРЦИИ (ВНЕ ЛЬДА). Как быстро лодка теряет скорость на блоках без льда.
# Это позволяет лодке "перелетать" небольшие разрывы.
# Чем МЕНЬШЕ значение, тем БЫСТРЕЕ лодка тормозит.
momentum-loss-factor: 0.92

# Включить режим отладки?
# Показывает текущий статус (на льду/вне льда) и скорость.
debug: false